name: Maven Build and Deploy to Tomcat

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'  # or 11/8 based on your project

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Clean project
      run: mvn clean

    - name: Package project
      run: mvn package

    - name: Deploy WAR to Tomcat
      uses: wei/curl@v1
      with:
        args: -u ${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASS }} \
              -T target/*.war \
              "http://44.203.55.18:8081/manager/text/deploy?path=/test&update=true"
